### ISSUE TITLE
Work generation - manifestations with same creator and original title

### ISSUE THREAD

**Issue by bensinober** [digibib/ls.ext#12]
Work should be generated when two or more manifestations have the same
a) creator - identified by URI
AND
b1) X and Y share same title and NO original title
OR
b2) title and NO original title on manifestation X equals original title on Y

**Comment by bensinober** [comment]
ontology and mapping updated with originalTitle. Work generation query rewritten to default to originalTitle and match on title when originalTitle not present.

More specifically, a BIND:
`BIND( IF( BOUND (?originalTitle ), ?originalTitle, ?title) as ?workTitle )`

tested by migration and using test dataset with a diff on result and expected result

**Comment by bensinober** [comment]
```

**Comment by bensinober** [comment]
Bibliofil  MARC poster   : 6
Bibliofil  Eksemplarer   : 69
Bibliofil  Lånere        : 3
Bibliofil  Lån           : 7
Bibliofil  Reserveringer : 1
Koha       MARC poster   : 6
Koha       Eksemplarer   : 69
Koha       Lånere        : 3
Koha       Lån           : 7
Koha       Reserveringer : 1
Marc2rdf   Publikasjoner : 6
Fuseki     Publikasjoner : 6
Fuseki     Verk          : 3
Fuseki     Personer      : 2
```

**Comment by boutros** [comment]
Spørringen for verksgenerering lager samme verk for pulikasjoner med samme tittel men ulike creators
Eks får disse to samme verk:
http://data.deichman.no/resource/tnr_29220.html
http://data.deichman.no/resource/tnr_29220.html

Jeg vil argumentere for at de kanskje bør være samme verk, men ikke at alle andre tilfeller av lik tittel, ulik forfatter vil treffe så god dessverre..

**Comment by boutros** [comment]
Kan ta dem inn i eksempeldatasettet, så har vi noe å teste mot?

**Comment by boutros** [comment]
Mulig dette fikser det
 https://github.com/digibib/migration/commit/301e808e9c919a9ad656755c69ec54c6d53ede51

**Comment by boutros** [comment]
Eller ikke, nå får jeg ingen verk...

**Comment by boutros** [comment]
Tror det skal være fikset med denne endringen: https://github.com/digibib/migration/commit/9928a702fb0c134bd7be75f152c416d778f56a70

**Comment by boutros** [comment]
Bekreftes med at filmen "Berlinerpoplene" får ulikt verk en boka "Berlinerpoplene" siden de har ulik creator

**Comment by bensinober** [comment]
deployet. bekreftet på demo ved søk på maria gripe og verk med originaltittel glasblåsorna
