### ISSUE TITLE
Sentralisér konfigurasjon av elasticsearch

### ISSUE THREAD

**Issue by kristom** [digibib/ls.ext#20]
Mappingfiler for elasticsearch' verk og personindekser er nå duplisert i tre like eksemplarsett; i salt, migration og i services. Det er stor fare for at de kommer ut av synk, og bør derfor ligge ett sted, fortrinnsvis i services. For at migration skal kunne resette indeks bør derfor derfor sletting av indekser og oppretting av mapping kunne gjøres om en tjeneste i services som migration kaller før migrering.

Løsningsforslag/grovskisse:

- person_mapping.json og work_mapping.json legges i services/.../resources
- Et nytt REST-endpoint  i services sørger for å laste opp disse til elasticsearch
- Endpointer kalles av migration

**Comment by boutros** [comment]
Veldig bra! 
Det er også delvis duplisert i en jenkins-jobb, så det skal bli bra å få eksponert dette i services.

**Comment by kristom** [comment]
Legger også til at man trigger reindeksering gjennom et REST-kall til services

**Comment by kristom** [comment]
Fikset i commit 29dc72e5450b5ccc5fdb4e4d11d8a7c1f7a1f9fc og ee4d694ee5b61abe1e481cd1eca8f6d1664ea04f
