### ISSUE TITLE
Felles js-kode for patron client og catalinker somegen npm-modul

### ISSUE THREAD

**Issue by kristom** [digibib/ls.ext#21]
Patron client og catalinker vil etter all sannsynlighet komme til å dele en del kode, f.eks. kode som velger foretrukket språkvariant av tittel og deltitel. Denne er for øyeblikket duplisert tre steder.

Løsningsforslag: Opprett en Node-modul i github/digibib med slike funksjoner.

**Comment by boutros** [comment]
forfølges i jira dersom det skal prioriteres
