### ISSUE TITLE
email_messaging.feature

### ISSUE THREAD

**Issue by bensinober** [digibib/ls.ext#22]
Feature: E-post meldinger

Scenario: Som bruker vil jeg kunne motta epostvarsler fra biblioteket om reserverte titler som er klare til avhenting

Scenario: Som bruker vil jeg kunne motta epostvarsler fra biblioteket om bøker som skulle vært levert

**Comment by asgeirr** [comment]
Scenario: Som bruker vil jeg ha forhåndsvarsel om forfall på e-post _n_ dager før lånetidens utløp.

Scenario: Som bruker vil jeg ha beskjed på e-post når det opprettes erstatningssak (et visst antall dager etter forfall)

Scenario: Som bruker vil jeg ha beskjed når en avdeling stenger, slik at materiale som stod til avhenting der må hentes på en annen avdeling.

Bør-krav:
Scenario: Som bruker vil jeg kunne velge som brukerinnstilling at kvittering for utlånt og innlevert materiale skal sendes på e-post

Scenario: Som bruker vil jeg, når jeg låner eller leverer inn materiale på automat, velge at kvittering blir sendt på e-post

Scenario: Som bruker vil jeg ha varsel ved utløp

**Comment by asgeirr** [comment]
Mer utfyllende liste:

Må-krav:
========

- Scenario: Som bruker vil jeg ha en velkomst e-post når jeg registrerer meg.
- Scenario: Som bruker vil jeg kunne motta epostvarsler fra biblioteket om reserverte titler som er klare til avhenting med referansenummer
- Scenario: Som bruker vil jeg kunne motta epostvarsler fra biblioteket om bøker som skulle vært levert både etter 7  og 21 dager.
- Scenario: Som bruker vil jeg ha forhåndsvarsel om forfall på e-post n dager før lånetidens utløp.
- Scenario: Som bruker vil jeg ha beskjed på e-post når det opprettes erstatningssak (et visst antall dager etter forfall)
- Scenario: Som bruker vil jeg ha beskjed når en avdeling stenger, slik at materiale som stod til avhenting der må hentes på en annen avdeling.
- Scenario: Som bruker vil jeg få en e-post med lenke til å opprette nytt passord hvis jeg har glemt passord når jeg skal logge inn.
- Scenario: Som ansatt vil jeg kunne sende egendefinerete meldinger til en gruppe brukere  (Tilhørende en avdeling)

Bør-krav: 
========

- Scenario: Som bruker vil jeg kunne velge som brukerinnstilling at kvittering for utlånt og innlevert materiale skal sendes på e-post
- Scenario: Som bruker vil jeg, når jeg låner eller leverer inn materiale på automat, velge at kvittering blir sendt på e-post
- Scenario: Som bruker vil jeg ha varsel ved lånetidens utløp, når det er reservasjon på materialet jeg lån
