### ISSUE TITLE
Velge flere verdier i feltene i catalinker

### ISSUE THREAD

**Issue by kristom** [digibib/ls.ext#23]
Som katalogisator vil jeg kunne registrere mer enn én verdi for felter der det er aktuelt:
- Språk
- Målgruppe
- biografisk innhold
- Format
- Litterær from
- Tilrettelegging (verk og utgivelse)
- Skriftsystem

**Comment by kristom** [comment]
Etter diskusjon med Bjørn Erik kom vi til at vi går for en løsning med muliplel-select, med søkestøtte i dropdown. Vi tenker i utgangspunktet å benytte [select2](https://select2.github.io) til dette.

**Comment by boutros** [comment]
forfølges i jira hvis det fremdeles er et problem
