### ISSUE TITLE
Kvittering for inn- og utlån på automat

### ISSUE THREAD

**Issue by bensinober** [digibib/ls.ext#4]
både papirkvittering og epost

**Comment by akafred** [comment]
Jeg flytter problemet fra #9 inn her:

hvis Koha SIPserver er satt med "utf-8" vil ikke kvitteringene og automaten vise norske ÆØÅ.
Hvis Koha SIPserver ikke er satt til "utf-8" og automaten IKKE har huket av Codepage 850 på skjermbilde 5/10 i automatoppsettet, vil norske ÆØÅ vises korrekt, men ikke-latinske tegn gir svada

Sannsynligvis en tegnsett-problematikk primært i automat og oppsett i Windows XP
