### ISSUE TITLE
Filtrere på filial

### ISSUE THREAD

**Issue by NichoP** [digibib/ls.ext#40]
Filtrering på filial i Patron Client.

Informasjonen må indekseres(?).

- [x] Avdelinger (Libraries) må kunne hentes fra Koha
- [x] Bug 16497 registrert. Skrive kode og pushe for signoff
- [ ] Indeks over eksemplarer tilgjengelig på avdeling

**Comment by boutros** [comment]
Foreløbig plan for å få indeksert filialer under verkets publikasjoner :
Planen er antageligvis ikke den beste og endelige løsning, men må begynne et sted... 

- [ ] Lage endpoint i services for bulk upload av triples
- [ ] Legg til steg i migrering som henter ut filialtilgjengelighet gruppert per biblioitem (SQL). Generer tripler basert på dette, og last opp via bulk upload i services
- [ ] Oppdater mapping og indeksering av verk til å ta med filialer under hver publikasjon
- [ ] Lag endpoint i services, som via koha recordID og payload av filialer - finner tilhørende verk, oppdaterer filialtriplene og reindekserer verket. 
- [ ] Lage cron job i koha som periodisk henter ut filialtilgjengelighet, og differ den mot den som ble hentet ut ved migrering. Da får vi enkelt en liste over recordID og filialer, som itereres over og trigger reindeksering via overnevte endpoint i services. I og med at cronjobben skal lagre state på disk, bør det havne i et volum. Enten et eget, eller f.eks mysql-volumet.

**Comment by boutros** [comment]
Foreløbig er det altså knn snakk om hvilke filialer som står oppført som holdingbranch av ett eller flere eksemplar av en publikasjon. Vi er fremdeles i tenkeboksen når det gjelder indeksering av informasjon om _faktisk_ tilgjengelighet basert på om ting er utlånt, i transit, til avhenting etc.

**Comment by boutros** [comment]
Nå er avdeling filtrerbart etter migrering, men gjenstår å sette opp synkronisering

**Comment by boutros** [comment]
Når skal synkroniseringen være i boks.

Det som ikke funker, som jeg kom på nå, er at endringer ikke fanges opp ved gjentatte migreringer. Det må jeg prøve å løse.

**Comment by boutros** [comment]
Ble selvføgelig no krøll med cronjobben - scriptet fikk ikke riktig filmodus.
Men selv når det er fiksa så ser det ikke ut til at cronjobben kjøres.
Vet ikke helt hvordan jeg kan debugge, siden cron logger til syslog, som ikke er tilgjengelig inne i containeren...

**Comment by boutros** [comment]
Fikk bekrefta at cron virker. Måtte bare vente :) (5 minutter er lengre en jeg trodde)
