### ISSUE TITLE
Mer nøyaktige eksemplarstatuser i patron-client

### ISSUE THREAD

**Issue by boutros** [digibib/ls.ext#50]
- [x] Oppdatert Koha REST API til å gi nødvendig informasjon

- [x] Endre services til å hente bibliografiske poster og eksemplardata fra REST APIet, og ikke fra /svc-apiet

- [x] Finne måte å provisjonere koha med katalogisatorbruker, som services må bruke

- [x] Oppdatere feilende featuretester

- [x] Oppdateringer av patron-client (avventer ny interaksjonsdesign)

**Comment by boutros** [comment]
Er godt i gang med første punkt på lista:
https://github.com/digibib/koha-salt-docker/commit/99d83ce80bbaf0fa12b1dbc4baa77335e9109656

**Comment by boutros** [comment]
Går nå løs på services, og endrer fra å bruke svc endpoint til nye rest endpoint

**Comment by boutros** [comment]
Nesten i mål med services: https://gist.github.com/boutros/034a0e92db315bedcbb4a7b6bd191bd2

**Comment by boutros** [comment]
Har fått alle featuretester grønne :)
Gjenstår å finne en måte å provisjonere katalogisatorbrukeren..

**Comment by boutros** [comment]
Regner også med at det blir en del endringer i patron-client, når det kommer en avklaring av hvordan eksemplarer og deres statuser og plasseringer skal vises

**Comment by boutros** [comment]
Litt overraskende så er det nye API treigere enn svc. Så da tror jeg at vi fremdeles skal bruke svc til å opprette poster, slik at ikke migreringstiden skal øke enda mer

**Comment by boutros** [comment]
Er også endel timeouts i koblingen services -> api
```HttpException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool: Unexpected error making the query: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
```

**Comment by bensinober** [comment]
Ikke så overraskende egentlig, siden APIet gjør en fetch på posten etter
oppretting.

https://github.com/digibib/koha-salt-docker/blob/master/koha-patched/patches/030-API-biblios-CRUD-expanded.patch

Kanskje unødvendig iom at Location header gir url til GET på posten. Den
kan enkelt fjernes. Da burde de være like raske.

Det som er mer interessant er concurrency. Mojolicious er en raskere og mer
robust webserver som bør gjøre det mulig med batchoppretting av poster.
F.eks. 10 poster/sek ville redusert migreringstiden betraktelig
8. jun. 2016 13:07 skrev "Petter Goksøyr Åsen" <notifications@github.com>:

**Comment by boutros** [comment]
> Ikke så overraskende egentlig, siden APIet gjør en fetch på posten etter
oppretting.

Aha, da er det ikke så rart. Har brukt Location header til å finne biblionumber, så da kan gjerne fetchen droppes. Jeg skal se på det. Det er kommet endel Plack-fikser i det siste, så tenkte å oppgradere koha-salt-docker nå uansett

**Comment by boutros** [comment]
Så vidt jeg kan se er det PUT `/api/v1/biblios/` som gjør en fetch etter oppdaterting, men ikke POST `api/v1/biblios` endpoint som brukes i migreringa.

**Comment by boutros** [comment]
Ser ut som `/svc` bruker en form for batch-prosessering, kanskje derfor det går raskere?

https://github.com/Koha-Community/Koha/blob/master/svc/import_bib#L69

**Comment by bensinober** [comment]
Ok, visste ikke at import_bib ble brukt. Vi kan jo lage et import-endepunkt
som gjør det samme. Som returnerer straks biblionumber er klart. Det burde
ikke ta mange ms

10. jun. 2016 08:00 skrev "Petter Goksøyr Åsen" <notifications@github.com>:
>
> Ser ut som /svc bruker en form for batch-prosessering, kanskje derfor det
går raskere?

**Comment by boutros** [comment]
Nei, jeg tok feil, det er vist `/svc/new_bib` vi brukte, men `import_bib` virker jo mer fristende :)

Tidsforskjellen mellom svc og nye api var som følger:

> [/svc]     Migrated 10000 publications through services in 1h7m45.667049956s
> [/api/v1] Migrated 9995 publications through services in 1h38m32.844898606s

**Comment by bensinober** [comment]
Men det er jo 1.7 sek per post! Hvordan kan det bruke så lang tid? Ved
separat test av POST til APIet brukte jeg Max 500ms. Hva med å stressteste
APIet? Høres ut som services lager masse overlay, sikkert pga
construct-spørringer og parsing av json respons fra APIet.
10. jun. 2016 10:00 skrev "Petter Goksøyr Åsen" <notifications@github.com>:

**Comment by boutros** [comment]
Ja det er klart, services gjør en del ekstra massering, tolking, og også en del ekstra spørringer til triplestore for å sjekke tilknytta ressurser..

**Comment by bensinober** [comment]
Ok. Så det vil uansett aldri komme under 1sek per post. Da skjønner jeg hva
du mener med millioner av http-request. Vi bør faktisk prøve separat
migrering/import. Siden marcxml er input i begge, og services ikke gjør
noen endringer
10. jun. 2016 10:34 skrev "Petter Goksøyr Åsen" <notifications@github.com>:
